/**
 * Write a `--patch` overlay that inserts this checkout's browserkit plugin by
 * absolute path.
 *
 * Why this exists: the Desktop profile is Electron-owned, so `dsh plugin add`
 * cannot touch it, and during development you usually want the plugin loaded
 * from the working tree rather than from an installed copy. A patch overlay row
 * takes an absolute module path, which is exactly that.
 *
 * Usage:
 *   node scripts/dev-overlay.mjs                 # writes .dev/overlay.cordis.patch.yml
 *   node scripts/dev-overlay.mjs --out custom.yml --headless false
 *   dsh --profile bt-verify --from-default-profile headless --patch .dev/overlay.cordis.patch.yml
 *
 * @module dsh-plugins/scripts/dev-overlay
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pluginEntry = path.join(repoRoot, 'packages', 'browserkit', 'lib', 'index.js');

/**
 * Read `--flag value` pairs from argv.
 *
 * @param {string[]} argv - process arguments after the script name.
 * @returns {Map<string, string>} parsed flags.
 */
function parseFlags(argv) {
  const flags = new Map();
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith('--')) continue;
    const value = argv[index + 1];
    if (value === undefined || value.startsWith('--')) {
      flags.set(token.slice(2), 'true');
      continue;
    }
    flags.set(token.slice(2), value);
    index += 1;
  }
  return flags;
}

const flags = parseFlags(process.argv.slice(2));
const outPath = path.resolve(repoRoot, flags.get('out') ?? '.dev/overlay.cordis.patch.yml');

// YAML is written by hand rather than pulled from a library: this repo must stay
// installable with no dependencies beyond the plugin's own.
const overlay = `# Generated by scripts/dev-overlay.mjs — do not commit.
# Insert the working-tree browserkit plugin by absolute path.
- insert:
    - id: browserkit
      name: '${pluginEntry.replace(/\\/gu, '/')}'
      config:
        headless: ${flags.get('headless') ?? 'true'}
        agent: ${flags.get('agent') ?? 'chrome'}
        allowEvaluate: ${flags.get('allow-evaluate') ?? 'true'}
`;

await mkdir(path.dirname(outPath), { recursive: true });
await writeFile(outPath, overlay, 'utf8');
console.log(`wrote ${outPath}`);
console.log(`entry ${pluginEntry}`);
